apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: statsd-exporter
  name: statsd-exporter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: statsd-exporter
    spec:
      containers:
      - image: davarski/chapter12k8s_statsd-exporter:latest
        name: statsd-exporter
        ports:
        - containerPort: 9102
        - containerPort: 9125
          protocol: UDP
        resources: {}
      restartPolicy: Always
status: {}
