version: '2'
services:

  gateway:
    container_name: simplebank-gateway
    restart: always
    build: ./gateway
    ports:
      - 5001:5000
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: simplebank.gateway

  orders:
    container_name: simplebank-orders
    restart: always
    build: ./orders
    ports:
      - 5002:5000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: simplebank.orders

  account-transactions:
    container_name: simplebank-account-transactions
    restart: always
    build: ./account_transactions
    ports:
      - 5003:5000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: simplebank.account

  fees:
    container_name: simplebank-fees
    restart: always
    build: ./fees
    ports:
      - 5004:5000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: simplebank.fees

  market:
    container_name: simplebank-market
    restart: always
    build: ./market
    ports:
      - 5005:5000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: simplebank.market

  rabbitmq:
    container_name: simplebank-rabbitmq
    image: deadtrickster/rabbitmq_prometheus
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    container_name: simplebank-redis
    image: redis
    ports:
      - "6380:6379"

  statsd-exporter:
    build: ./statsd-exporter
    ports:
      - "9102:9102"
      - "9125:9125/udp"

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"

  statsd:
    build: ./statsd
    ports:
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    build: ./grafana
    ports:
      - "3900:3000"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  alerts:
    container_name: simplebank-alerts
    restart: always
    build: ./alerts
    ports:
      - 5006:5000

